import assert from 'node:assert/strict'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const dist = resolve(root, 'dist')
const check = process.argv.includes('--check')

// Follow the emitted module graph, including re-exports and lazy imports.
// External package classes belong to their own CSS entry, never our sources.
async function sources(entry) {
    const build = await Bun.build({
        entrypoints: [resolve(dist, entry)],
        target: 'browser',
        packages: 'external',
        write: false,
        metafile: true,
    })
    assert.ok(build.success, String(build.logs))
    const paths = Object.keys(build.metafile.inputs).map((path) =>
        resolve(root, path),
    )
    for (const path of paths)
        assert.ok(path.startsWith(dist + sep), `Source outside dist: ${path}`)
    return paths
        .toSorted()
        .map((path) =>
            relative(resolve(root, 'styles'), path).split(sep).join('/'),
        )
}

await Promise.all(
    Object.entries({
        input: 'shared/Inputs/Components/CustomInput.js',
        'text-input': 'shared/Inputs/Components/Inputs/TextInput.js',
    }).map(async ([name, entry]) => {
        const path = resolve(root, 'styles', `${name}.css`)
        const css = [
            '/* Generated by scripts/build-css.mjs from reachable dist modules. */',
            "@import '@rentnerkev/tooltips/tailwind.css';",
            "@import './theme.css';",
            '',
            ...(await sources(entry)).map((source) => `@source "${source}";`),
            '',
        ].join('\n')
        if (check)
            assert.equal(
                readFileSync(path, 'utf8'),
                css,
                `Stale CSS source graph: ${name}`,
            )
        else writeFileSync(path, css)
    }),
)
